- hosts: vb
  tasks:
       - yum_repository:
               name: dockername
               description: configuring docker with yum
               baseurl: https://download.docker.com/linux/centos/7/x86_64/stable/
               gpgcheck: "no"
       - name: Installing Docker
         package:
               name: "docker-ce-18.09.1-3.el7.x86_64"
               state: present
       - service:
               name: "docker"
               state: started
       - pip:
               name: docker-py
       - name: pulling the docker image from docker hub
         docker_image:
               name: httpd
               source: pull
       - name: copying file html file into home
         copy:
               dest: /home/index.html
               content: "This is webpage configured by ansible for docker"
       - name: creating a docker container for webserver
         community.general.docker_container:
               name: webserver
               image: httpd
               ports: "8081:80"
               state: started
               detach: yes
               volumes: /home/:/usr/local/apache2/htdocs/
