- hosts: vb
  tasks:
       - yum_repository:
               name: dockername
               description: configuring docker with yum
               baseurl: https://download.docker.com/linux/centos/7/x86_64/stable/
               gpgcheck: "no"
       - name: Installing Docker
         package:
               name: "docker-ce-18.09.1-3.el7.x86_64"
               state: present
       - service:
               name: "docker"
               state: started
       - pip:
               name: docker-py
       - name: pulling the docker image from docker hub
         docker_image:
               name: sainadh086/webserver:latest
               source: pull
       - name: copying file html file into home
         copy:
               dest: /home/index.html
               content: "This webpage is configured by ansible"
       - name: creating a docker container for webserver
         docker_container:
               name: web
               image: sainadh086/webserver
               #ports: 
               # - "8081:80"
               volumes: 
                 - /home/:/var/www/html/
               command: sleep 1d
